# 仅此一个参数传入脚本。缺省项自动使用默认值。
# 示例：python main.py config.yaml

# 数据与模型
#train_path: /workspace/Gjj Local/data/kaggle/Classification with an Academic Success Dataset/train.csv
#test_path: /workspace/Gjj Local/data/kaggle/Classification with an Academic Success Dataset/test.csv
train_path: /workspace/Gjj Local/data/kaggle/Binary Classification with a Bank Dataset/train.csv
test_path: /workspace/Gjj Local/data/kaggle/Binary Classification with a Bank Dataset/test.csv
ckpt_path: /workspace/Gjj Local/data/tabcil/ckpt/tabicl-classifier-v1.1-0506.ckpt

# ICL 支持样本控制
ICL_MAX_SAMPLES: 18000   # 0 或 None 表示使用全部
ICL_SAMPLE_RANDOM: true # true 随机抽样；false 取前N
SEED: 42
NEED_GET_ACC: false
NEED_GET_SUBMISSION: true
#LABEL_COL: Target
LABEL_COL: y

# 提交文件保存位置
submission_path: ./submission.csv
